00. Getting started with TensorFlow: A guide to the fundamentals

What is TensorFlow? 

TensorFlow is an open-source end-to-end machine learning library for preprocessing data, modelling data and serving models (getting them into the hands of others).

In [120]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.20.0


In [68]:
#Create tensor with tf.scalar()
scalar=tf.constant(5)
print(scalar)

tf.Tensor(5, shape=(), dtype=int32)


In [69]:
#Check the number of dimensions 
print(scalar.ndim)

0


In [19]:
#create a vector2
vector=tf.constant([5,19,32,232,1231,1313,131,11111111111])
vector

<tf.Tensor: shape=(8,), dtype=int64, numpy=
array([          5,          19,          32,         232,        1231,
              1313,         131, 11111111111])>

In [70]:
vector.ndim

1

In [80]:
my_vector=tf.constant([[1,2,3,4],
                      [4,5,6,4],
                      [7,8,9,4]])
my_vector

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [4, 5, 6, 4],
       [7, 8, 9, 4]], dtype=int32)>

In [77]:
my_vector.ndim

2

In [85]:
another_vector=tf.constant([[1.,2.],
                            [3.,4.],
                          [5.,6.]], tf.float16)
another_vector

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [87]:
tensor=tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                      [10,11,12]]],)
tensor.ndim

3

In [96]:
changed=tf.Variable([10,20,30])
unchanged=tf.constant([10,20,50])
changed, unchanged

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 20, 30], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 50], dtype=int32)>)

In [108]:
changed=tf.Variable([10,20,30],name="my_variable")
changed.assign([1,2,4])
changed

<tf.Variable 'my_variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 4], dtype=int32)>

** Uniform distribution is a distrubution that has constant propability//toate valorile la fel de probabile/// 
Exemplu :Zarul
**Normală = valorile se adună în centru, forma de clopot
Exemplu:inaltimea oamenilor 

In [138]:
random1=tf.random.Generator.from_seed(42)
random1=random1.normal(shape=(3,2))
random2=tf.random.Generator.from_seed(42)
random2=random2.normal(shape=(3,2))
random1,random2, random1==random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [168]:
tf.random.set_seed(42)
a=tf.random.shuffle(random1,seed=42)
a   

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [171]:
tf.ones(shape=(2,3))
tf.zeros(shape=(2,6))

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

🔑 Note: A matrix or tensor is typically represented by a capital letter (e.g. X or A) where as a vector is typically represented by a lowercase letter (e.g. y or b).

In [174]:
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [176]:
A=tf.constant(numpy_A,shape=((2,3,4)))
B=tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

Getting information from tensors (shape, rank, size)

There will be times when you'll want to get different pieces of information from your tensors, in particuluar, you should know the following tensor vocabulary:

Shape: The length (number of elements) of each of the dimensions of a tensor.

Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.

Axis or Dimension: A particular dimension of a tensor.

Size: The total number of items in the tensor.

In [183]:
rank4_tensor=tf.zeros(shape=(2,3,4,5))
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [180]:
rank4_tensor.ndim,rank4_tensor.shape,tf.size(rank4_tensor)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [184]:
print("Datatype of rank4_tensor:",rank4_tensor.dtype)
print("number of dimensions:",rank4_tensor.ndim)
print("shape of tensor:",rank4_tensor.shape)
print("Elements along axis 0:",rank4_tensor.shape[0])
print("Elements along last axis:",rank4_tensor.shape[-1])
print("Total number of elements in tensor:",tf.size(rank4_tensor).numpy())

Datatype of rank4_tensor: <dtype: 'float32'>
number of dimensions: 4
shape of tensor: (2, 3, 4, 5)
Elements along axis 0: 2
Elements along last axis: 5
Total number of elements in tensor: 120


In [192]:
# Get the dimension from each index except for the final one
rank4_tensor[:1, :1, :1, :].numpy()
rank4_tensor[:, :, :1, :]

<tf.Tensor: shape=(2, 3, 1, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [193]:
#create a rank2 tensor (2 dimensions)
rank2_tensor=tf.constant([[10,20],
                           [30,40]])
rank2_tensor.ndim,rank2_tensor.shape

(2, TensorShape([2, 2]))

In [194]:
## Get the last item of each row
rank2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 40], dtype=int32)>

In [202]:
#add in extra dimension  to our rank 2 tensor
rank3_tensor=rank2_tensor[...,tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [20]],

       [[30],
        [40]]], dtype=int32)>

In [206]:
tf.expand_dims(rank2_tensor,axis=-1)#expand the final axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [20]],

       [[30],
        [40]]], dtype=int32)>

## Manipulating tensors (tensor operations)


Since we used `tf.constant()`, the original tensor is unchanged (the addition gets done on a copy).

In [222]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor+10 # but if i print this is a copy of the tensor with 10 added to each element

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [224]:
tensor # if i wann prit this is unchanged because of the constant nature of tensors

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [225]:
tensor * 10,tensor - 10,tf.multiply(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>)

In [226]:
# The original tensor is still unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

The main two rules for matrix multiplication to remember are:
1. The inner dimensions must match:
  * `(3, 5) @ (3, 5)` won't work
  * `(5, 3) @ (3, 5)` will work
  * `(3, 5) @ (5, 3)` will work
2. The resulting matrix has the shape of the outer dimensions:
 * `(5, 3) @ (3, 5)` -> `(5, 5)`
 * `(3, 5) @ (5, 3)` -> `(3, 3)`

> 🔑 **Note:** '`@`' in Python is the symbol for matrix multiplication.


In [227]:
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

> 🔑 **Note:** '`@`' in Python is the symbol for matrix multiplication.
* And tensor @ tensor is different to tensor * tensor 

In [239]:
print("the first matrix:\n",tensor.numpy())
print("the secodn matrix:\n",tensor.numpy())
print("The difference between @ and * :\n")
print(tensor @ tensor) # matrix multiplication
print()
print(tensor * tensor) # element-wise multiplication

the first matrix:
 [[10  7]
 [ 3  4]]
the secodn matrix:
 [[10  7]
 [ 3  4]]
The difference between @ and * :

tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[100  49]
 [  9  16]], shape=(2, 2), dtype=int32)


In [241]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X@Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [243]:
X,tf.reshape(X, shape=(2,3)) # this is making a copy of X reshaped to 2,3

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [247]:
X,Y,X @ tf.reshape(Y,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>)

In [250]:
# Try matrix multiplication 
tf.transpose(X),Y, tf.matmul(tf.transpose(X), Y)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]], dtype=int32)>)

In [251]:
tf.matmul(a=X, b=Y,transpose_a=True,transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [252]:
tf.matmul(a=X, b=Y,transpose_a=False,transpose_b=True)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

You can perform the `tf.matmul()` operation using [`tf.tensordot()`]

In [256]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [257]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [258]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [259]:
# Check shapes of Y, reshaped Y and tranposed Y
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [260]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [262]:
import tensorflow as tf

# Date de test
X = tf.constant([[1, 2], [3, 4]])
Y = tf.constant([[5, 6], [7, 8]])
A = tf.constant([[1.0, 2.0], [3.0, 4.0]])
vector = tf.constant([7, 8, 9, 10, 11, 12])

print("=== VARIABILELE INITIALE ===")
print("X:", X.numpy())
print("Y:", Y.numpy())
print("A:", A.numpy())
print("vector:", vector.numpy())
print()

print("1. tf.reshape()")
print("vector reshape la (2, 3):")
print(tf.reshape(vector, (2, 3)).numpy())
print("Shape:", tf.reshape(vector, (2, 3)).shape)
print()

print("2. tf.transpose()")
print("X transpus:")
print(tf.transpose(X).numpy())
print()

print("3. tf.tensordot() - axes=1")
print("tf.tensordot(X, Y, axes=1):")
print(tf.tensordot(X, Y, axes=1).numpy())
print()

print("4. tf.matmul()")
print("X * Y (înmulțire matriceală):")
print(tf.matmul(X, Y).numpy())
print()

print("5. tf.add()")
print("X + Y (adunare element-wise):")
print(tf.add(X, Y).numpy())
print()

print("6. tf.multiply()")
print("X * Y (înmulțire element-wise):")
print(tf.multiply(X, Y).numpy())
print()

print("7. tf.linalg.inv() - Inversă matrice")
print("A inversă:")
print(tf.linalg.inv(A).numpy())
print()

print("8. tf.linalg.det() - Determinant")
print("det(A):", tf.linalg.det(A).numpy())
print()

print("9. tf.eye() - Matrice identitate")
print("Matrice identitate 3x3:")
print(tf.eye(3).numpy())
print()

print("10. tf.zeros() / tf.ones()")
print("Matrice zerouri 2x3:")
print(tf.zeros((2, 3)).numpy())
print("Matrice unu-ri 2x2:")
print(tf.ones((2, 2)).numpy())

=== VARIABILELE INITIALE ===
X: [[1 2]
 [3 4]]
Y: [[5 6]
 [7 8]]
A: [[1. 2.]
 [3. 4.]]
vector: [ 7  8  9 10 11 12]

1. tf.reshape()
vector reshape la (2, 3):
[[ 7  8  9]
 [10 11 12]]
Shape: (2, 3)

2. tf.transpose()
X transpus:
[[1 3]
 [2 4]]

3. tf.tensordot() - axes=1
tf.tensordot(X, Y, axes=1):
[[19 22]
 [43 50]]

4. tf.matmul()
X * Y (înmulțire matriceală):
[[19 22]
 [43 50]]

5. tf.add()
X + Y (adunare element-wise):
[[ 6  8]
 [10 12]]

6. tf.multiply()
X * Y (înmulțire element-wise):
[[ 5 12]
 [21 32]]

7. tf.linalg.inv() - Inversă matrice
A inversă:
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]

8. tf.linalg.det() - Determinant
det(A): -2.0

9. tf.eye() - Matrice identitate
Matrice identitate 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

10. tf.zeros() / tf.ones()
Matrice zerouri 2x3:
[[0. 0. 0.]
 [0. 0. 0.]]
Matrice unu-ri 2x2:
[[1. 1.]
 [1. 1.]]


In [266]:
B=tf.constant([1.7,7.4])
B.dtype
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B
B=tf.cast(B, dtype=tf.float32)
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7001953, 7.3984375], dtype=float32)>

In [268]:
D = tf.constant([-7, -10])

D,tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)


To do so, aggregation methods typically have the syntax `reduce()_[action]`, such as:
* [`tf.reduce_min()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min) - find the minimum value in a tensor.
* [`tf.reduce_max()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max) - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
* [`tf.reduce_mean()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean) - find the mean of all elements in a tensor.
* [`tf.reduce_sum()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum) - find the sum of all elements in a tensor.
* **Note:** typically, each of these is under the `math` module, e.g. `tf.math.reduce_min()` but you can use the alias `tf.reduce_min()`.
* [`tf.argmax()`](https://www.tensorflow.org/api_docs/python/tf/math/argmax) - find the position of the maximum element in a given tensor.
* [`tf.argmin()`](https://www.tensorflow.org/api_docs/python/tf/math/argmin) - find the position of the minimum element in a given tensor.
* [`tf.squeeze()`](https://www.tensorflow.org/api_docs/python/tf/squeeze) - remove all dimensions of 1 from a tensor.

In [269]:
E=tf.constant(np.random.randint(1,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([65, 62, 93, 35, 56, 89, 13, 83, 40, 48, 67, 24, 84, 63, 39, 76, 26,
       18, 80, 77,  2, 21, 24,  2, 21, 40, 66, 78, 32,  9, 69, 59, 21, 28,
       33, 26, 10, 26, 59, 37, 25, 26, 75, 78, 58, 20,  9, 81, 58, 78],
      dtype=int32)>

In [276]:
tf.reduce_min(E), tf.reduce_max(E), tf.reduce_mean(E),tf.reduce_mean(E).numpy(),tf.reduce_sum(E).numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=93>,
 <tf.Tensor: shape=(), dtype=int32, numpy=46>,
 np.int32(46),
 np.int32(2309))

In [277]:
F = tf.constant(np.random.randint(1,50,50))
F

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([28, 29, 30, 48, 41, 38,  8, 15, 39, 25,  2,  3, 31, 43, 15, 17,  3,
       14,  4, 25, 34, 40, 39, 16, 42, 28, 49, 11, 27, 33, 37,  3,  8, 10,
       11, 16, 21, 15,  4, 23, 32, 13,  3, 25, 14, 22, 21, 34, 27, 49],
      dtype=int32)>

In [289]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")



The maximum value of F is at position: 26
The maximum value of F is: 49
Using tf.argmax() to index F, the maximum value of F is: 49
Are the two max values the same (they should be)? True


In [294]:
G = tf.constant(np.random.randint(0, 100, 50), shape=(2, 1, 1, 1, 25))
G.shape, G.ndim,G

(TensorShape([2, 1, 1, 1, 25]),
 5,
 <tf.Tensor: shape=(2, 1, 1, 1, 25), dtype=int32, numpy=
 array([[[[[30, 88, 46, 48, 45, 51, 14, 33, 95, 98, 47, 64, 29, 31, 17,
            31, 49, 38, 42, 69, 81, 35, 78,  6, 62]]]],
 
 
 
        [[[[93, 49, 93,  2, 61, 28, 40, 69, 81, 46, 29, 23, 50, 11,  4,
             2,  6, 46, 31, 46, 46, 73, 69, 71,  3]]]]], dtype=int32)>)

* [`tf.squeeze()`](https://www.tensorflow.org/api_docs/python/tf/squeeze) - remove all dimensions of 1 from a tensor.

In [295]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([2, 25]), 2)

In [306]:
# Create a list of indices
some_list = [0, 2, 2, 1]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]], dtype=float32)>

## Using `@tf.function`

In [322]:
# Create a simple function
@tf.function
def function(x,y):
    return tf.tensordot(x,y,axes=1)

x=tf.constant([1,2,3,4])
y=tf.constant([5,6,7,8])
t=tf.reshape(y,(4,1))
rez=function(x,t)
rez

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([70], dtype=int32)>

In [307]:
print(tf.config.list_physical_devices('GPU'))

[]


## 🛠 Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [324]:
#1.
vector=tf.constant([1,2,3,4,5])
scalar=tf.constant(5)
matrix=tf.constant([[1,2,3],
                    [4,5,6]])
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]]])
vector,scalar,matrix,tensor

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>)

In [336]:
# 2. Correct way:
print("Vector - Shape:", vector.shape, "Rank:", tf.rank(vector).numpy(), "Size:", tf.size(vector).numpy())
print("Scalar - Shape:", scalar.shape, "Rank:", tf.rank(scalar).numpy(), "Size:", tf.size(scalar).numpy())
print("Matrix - Shape:", matrix.shape, "Rank:", tf.rank(matrix).numpy(), "Size:", tf.size(matrix).numpy())
print("Tensor - Shape:", tensor.shape, "Rank:", tf.rank(tensor).numpy(), "Size:", tf.size(tensor).numpy())

Vector - Shape: (5,) Rank: 1 Size: 5
Scalar - Shape: () Rank: 0 Size: 1
Matrix - Shape: (2, 3) Rank: 2 Size: 6
Tensor - Shape: (2, 2, 3) Rank: 3 Size: 12


In [338]:
#3.Create two tensors containing random values between 0 and 1 with shape `[5, 300]`
tensor1=tf.random.uniform(shape=(5,300), minval=0, maxval=1)
tensor2=tf.random.uniform(shape=(5,300), minval=0, maxval=1)
tensor3=tf.constant(np.random.randint(1,50,10))
tensor1,tensor2,tensor3

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
         0.25082767],
        [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
         0.28176582],
        [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
         0.9987265 ],
        [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
         0.1740731 ],
        [0.90936875, 0.19861352, 0.9481231 , ..., 0.3573054 , 0.13161755,
         0.22565222]], shape=(5, 300), dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7402308 , 0.33938193, 0.5692506 , ..., 0.08656633, 0.19666708,
         0.7110305 ],
        [0.13257599, 0.81292987, 0.01284087, ..., 0.02695906, 0.2927854 ,
         0.06227863],
        [0.282601  , 0.47868013, 0.77569485, ..., 0.28239357, 0.632112  ,
         0.44452012],
        [0.02029276, 0.7841259 , 0.16919017, ..., 0.26143157, 0.43055534,
         0.47421408],


In [345]:
#4. Multiply the two tensors you created in 3 using matrix multiplication.
tf.matmul(tensor1,tf.transpose(tensor2))
tensor1 @tf.transpose(tensor2)
tf.matmul(a=tensor1,b=tensor2,transpose_b=True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.63513 , 73.275154, 72.47874 , 73.895355, 77.06909 ],
       [76.148026, 77.38722 , 76.156006, 78.4779  , 77.93587 ],
       [74.061386, 75.79873 , 74.00405 , 74.954445, 74.857666],
       [72.6186  , 77.07387 , 72.674484, 75.91608 , 73.15646 ],
       [74.65547 , 76.221756, 75.43701 , 76.92053 , 76.65762 ]],
      dtype=float32)>

In [355]:
#5. Multiply the two tensors you created in 3 using dot product.
tf.tensordot(tensor1,tf.transpose(tensor2),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.63513 , 73.275154, 72.47874 , 73.895355, 77.06909 ],
       [76.148026, 77.38722 , 76.156006, 78.4779  , 77.93587 ],
       [74.061386, 75.79873 , 74.00405 , 74.954445, 74.857666],
       [72.6186  , 77.07387 , 72.674484, 75.91608 , 73.15646 ],
       [74.65547 , 76.221756, 75.43701 , 76.92053 , 76.65762 ]],
      dtype=float32)>

In [ ]:
a=tf.random.uniform(shape=([224, 224, 3]),minval=0,maxval=1)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.95831835, 0.01680839, 0.3156035 ],
        [0.16013157, 0.7148702 , 0.7892921 ],
        [0.11484027, 0.33310425, 0.21091413],
        ...,
        [0.6279857 , 0.85051286, 0.9490392 ],
        [0.62438786, 0.2802421 , 0.18754554],
        [0.9087832 , 0.46846092, 0.5317346 ]],

       [[0.85744655, 0.51288927, 0.18603599],
        [0.04882693, 0.78045344, 0.79377043],
        [0.9356363 , 0.32798207, 0.15949786],
        ...,
        [0.6933085 , 0.5420611 , 0.1860913 ],
        [0.7326596 , 0.9234495 , 0.07200372],
        [0.5471792 , 0.24985266, 0.14673471]],

       [[0.5033684 , 0.7000841 , 0.21468806],
        [0.9304948 , 0.17212296, 0.720364  ],
        [0.6657183 , 0.17304075, 0.7110392 ],
        ...,
        [0.35423398, 0.126225  , 0.24436975],
        [0.096439  , 0.06387579, 0.32836854],
        [0.15067935, 0.6084572 , 0.47766674]],

       ...,

       [[0.23573959, 0.42224514, 0.9151635 ],
        [0.38

In [360]:
#7. Find the min and max values of the tensor you created in 6.
tf.reduce_min(a),tf.reduce_max(a)

(<tf.Tensor: shape=(), dtype=float32, numpy=-1.8107855319976807>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0759502574801445>)

In [364]:
#8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
b=tf.random.uniform(shape=([1,224,224,3]))
new_b=tf.squeeze(b)
new_b

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.12780273, 0.86230123, 0.41563296],
        [0.10028672, 0.6078365 , 0.79052174],
        [0.06068337, 0.85674644, 0.72001266],
        ...,
        [0.42501688, 0.777889  , 0.7029644 ],
        [0.00265503, 0.4391595 , 0.89044964],
        [0.63493025, 0.87544703, 0.943701  ]],

       [[0.6613052 , 0.37710202, 0.51483595],
        [0.50989354, 0.9679649 , 0.45765674],
        [0.2590027 , 0.3557694 , 0.26365137],
        ...,
        [0.3261726 , 0.49975753, 0.1813755 ],
        [0.6064073 , 0.8051214 , 0.320701  ],
        [0.32923293, 0.5298729 , 0.39044487]],

       [[0.34140837, 0.47335994, 0.01272404],
        [0.47659898, 0.47509444, 0.8660991 ],
        [0.16929126, 0.09049737, 0.09263301],
        ...,
        [0.15332878, 0.2546159 , 0.9531114 ],
        [0.10869956, 0.5302429 , 0.8690088 ],
        [0.6384195 , 0.19085515, 0.35851824]],

       ...,

       [[0.62105274, 0.22180116, 0.71062243],
        [0.27

In [375]:
#9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
c=tf.random.uniform(shape=(10,),minval=1,maxval=10,dtype=tf.int32)
d=tf.argmax(c)
c,d

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([4, 1, 6, 9, 3, 5, 5, 5, 3, 3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=3>)

In [376]:
#10. One-hot encode the tensor you created in 9.
tf.one_hot(c,depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>


To do so, aggregation methods typically have the syntax `reduce()_[action]`, such as:
* [`tf.reduce_min()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min) - find the minimum value in a tensor.
* [`tf.reduce_max()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max) - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
* [`tf.reduce_mean()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean) - find the mean of all elements in a tensor.
* [`tf.reduce_sum()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum) - find the sum of all elements in a tensor.
* **Note:** typically, each of these is under the `math` module, e.g. `tf.math.reduce_min()` but you can use the alias `tf.reduce_min()`.
* [`tf.argmax()`](https://www.tensorflow.org/api_docs/python/tf/math/argmax) - find the position of the maximum element in a given tensor.
* [`tf.argmin()`](https://www.tensorflow.org/api_docs/python/tf/math/argmin) - find the position of the minimum element in a given tensor.
* [`tf.squeeze()`](https://www.tensorflow.org/api_docs/python/tf/squeeze) - remove all dimensions of 1 from a tensor.

In [377]:
import tensorflow as tf

# Date de test
X = tf.constant([[1, 2], [3, 4]])
Y = tf.constant([[5, 6], [7, 8]])
A = tf.constant([[1.0, 2.0], [3.0, 4.0]])
vector = tf.constant([7, 8, 9, 10, 11, 12])

print("=== VARIABILELE INITIALE ===")
print("X:", X.numpy())
print("Y:", Y.numpy())
print("A:", A.numpy())
print("vector:", vector.numpy())
print()

print("1. tf.reshape()")
print("vector reshape la (2, 3):")
print(tf.reshape(vector, (2, 3)).numpy())
print("Shape:", tf.reshape(vector, (2, 3)).shape)
print()

print("2. tf.transpose()")
print("X transpus:")
print(tf.transpose(X).numpy())
print()

print("3. tf.tensordot() - axes=1")
print("tf.tensordot(X, Y, axes=1):")
print(tf.tensordot(X, Y, axes=1).numpy())
print()

print("4. tf.matmul()")
print("X * Y (înmulțire matriceală):")
print(tf.matmul(X, Y).numpy())
print()

print("5. tf.add()")
print("X + Y (adunare element-wise):")
print(tf.add(X, Y).numpy())
print()

print("6. tf.multiply()")
print("X * Y (înmulțire element-wise):")
print(tf.multiply(X, Y).numpy())
print()

print("7. tf.linalg.inv() - Inversă matrice")
print("A inversă:")
print(tf.linalg.inv(A).numpy())
print()

print("8. tf.linalg.det() - Determinant")
print("det(A):", tf.linalg.det(A).numpy())
print()

print("9. tf.eye() - Matrice identitate")
print("Matrice identitate 3x3:")
print(tf.eye(3).numpy())
print()

print("10. tf.zeros() / tf.ones()")
print("Matrice zerouri 2x3:")
print(tf.zeros((2, 3)).numpy())
print("Matrice unu-ri 2x2:")
print(tf.ones((2, 2)).numpy())

=== VARIABILELE INITIALE ===
X: [[1 2]
 [3 4]]
Y: [[5 6]
 [7 8]]
A: [[1. 2.]
 [3. 4.]]
vector: [ 7  8  9 10 11 12]

1. tf.reshape()
vector reshape la (2, 3):
[[ 7  8  9]
 [10 11 12]]
Shape: (2, 3)

2. tf.transpose()
X transpus:
[[1 3]
 [2 4]]

3. tf.tensordot() - axes=1
tf.tensordot(X, Y, axes=1):
[[19 22]
 [43 50]]

4. tf.matmul()
X * Y (înmulțire matriceală):
[[19 22]
 [43 50]]

5. tf.add()
X + Y (adunare element-wise):
[[ 6  8]
 [10 12]]

6. tf.multiply()
X * Y (înmulțire element-wise):
[[ 5 12]
 [21 32]]

7. tf.linalg.inv() - Inversă matrice
A inversă:
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]

8. tf.linalg.det() - Determinant
det(A): -2.0

9. tf.eye() - Matrice identitate
Matrice identitate 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

10. tf.zeros() / tf.ones()
Matrice zerouri 2x3:
[[0. 0. 0.]
 [0. 0. 0.]]
Matrice unu-ri 2x2:
[[1. 1.]
 [1. 1.]]


In [1]:
import tensorflow as tf
import numpy as np

print("=== TensorFlow Exercises - Complete Solution ===\n")

# 1. Create vector, scalar, matrix and tensor
print("1. Vector, scalar, matrix and tensor:")
vector = tf.constant([1, 2, 3, 4, 5])
scalar = tf.constant(5)
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(f"Vector: {vector.numpy()}")
print(f"Scalar: {scalar.numpy()}")
print(f"Matrix: {matrix.numpy()}")
print(f"Tensor: {tensor.numpy()}")
print()

# 2. Find shape, rank and size
print("2. Shape, rank and size:")
print(f"Vector - shape: {vector.shape}, rank: {tf.rank(vector).numpy()}, size: {tf.size(vector).numpy()}")
print(f"Scalar - shape: {scalar.shape}, rank: {tf.rank(scalar).numpy()}, size: {tf.size(scalar).numpy()}")
print(f"Matrix - shape: {matrix.shape}, rank: {tf.rank(matrix).numpy()}, size: {tf.size(matrix).numpy()}")
print(f"Tensor - shape: {tensor.shape}, rank: {tf.rank(tensor).numpy()}, size: {tf.size(tensor).numpy()}")
print()

# 3. Create two tensors with shape [5, 300]
print("3. Two random tensors shape [5, 300]:")
tensor1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
tensor2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
print(f"Tensor1 shape: {tensor1.shape}")
print(f"Tensor2 shape: {tensor2.shape}")
print()

# 4. Matrix multiplication
print("4. Matrix multiplication:")
matrix_mult = tf.matmul(tensor1, tensor2, transpose_b=True)
print(f"Matrix multiplication result shape: {matrix_mult.shape}")
print()

# 5. Dot product (element-wise)
print("5. Dot product (element-wise):")
dot_product = tensor1 * tensor2
print(f"Dot product result shape: {dot_product.shape}")
print()

# 6. Create tensor with shape [224, 224, 3]
print("6. Tensor shape [224, 224, 3]:")
a = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
print(f"Image tensor shape: {a.shape}")
print()

# 7. Find min and max values
print("7. Min and max values:")
print(f"Min value: {tf.reduce_min(a).numpy()}")
print(f"Max value: {tf.reduce_max(a).numpy()}")
print()

# 8. Create and squeeze tensor
print("8. Create and squeeze tensor:")
b = tf.random.uniform(shape=[1, 224, 224, 3], minval=0, maxval=1)
new_b = tf.squeeze(b)
print(f"Original shape: {b.shape}")
print(f"Squeezed shape: {new_b.shape}")
print()

# 9. Create tensor with shape [10] and find max index
print("9. Tensor with max index:")
c = tf.random.uniform(shape=[10], minval=0, maxval=100, dtype=tf.int32)
d = tf.argmax(c)
print(f"Tensor: {c.numpy()}")
print(f"Max value index: {d.numpy()}")
print()

# 10. One-hot encode
print("10. One-hot encoding:")
one_hot_encoded = tf.one_hot(c, depth=100)
print(f"One-hot encoded shape: {one_hot_encoded.shape}")
print(f"One-hot encoded (first 3 rows):\n{one_hot_encoded[:3].numpy()}")

=== TensorFlow Exercises - Complete Solution ===

1. Vector, scalar, matrix and tensor:
Vector: [1 2 3 4 5]
Scalar: 5
Matrix: [[1 2 3]
 [4 5 6]]
Tensor: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

2. Shape, rank and size:
Vector - shape: (5,), rank: 1, size: 5
Scalar - shape: (), rank: 0, size: 1
Matrix - shape: (2, 3), rank: 2, size: 6
Tensor - shape: (2, 2, 3), rank: 3, size: 12

3. Two random tensors shape [5, 300]:
Tensor1 shape: (5, 300)
Tensor2 shape: (5, 300)

4. Matrix multiplication:
Matrix multiplication result shape: (5, 5)

5. Dot product (element-wise):
Dot product result shape: (5, 300)

6. Tensor shape [224, 224, 3]:
Image tensor shape: (224, 224, 3)

7. Min and max values:
Min value: 4.410743713378906e-06
Max value: 0.9999985694885254

8. Create and squeeze tensor:
Original shape: (1, 224, 224, 3)
Squeezed shape: (224, 224, 3)

9. Tensor with max index:
Tensor: [60 46 76 56 32 96 47  8 80 51]
Max value index: 5

10. One-hot encoding:
One-hot encoded shape: 

In [379]:
import tensorflow as tf

# === TENSOR CREATION ===
print("=== TENSOR CREATION ===")
# tf.constant() - create tensors with fixed values
# tf.random.uniform() - create tensors with random values from uniform distribution
# tf.random.normal() - create tensors with random values from normal distribution
# tf.range() - create tensors with sequences
# tf.zeros() - create tensors filled with zeros
# tf.ones() - create tensors filled with ones

# === TENSOR PROPERTIES ===
print("\n=== TENSOR PROPERTIES ===")
# .shape - get tensor shape
# tf.rank() - get tensor rank (number of dimensions)
# tf.size() - get total number of elements
# .dtype - get data type

# === TENSOR OPERATIONS ===
print("\n=== TENSOR OPERATIONS ===")
# tf.matmul() - matrix multiplication
# @ operator - matrix multiplication
# * operator - element-wise multiplication
# tf.multiply() - element-wise multiplication
# tf.transpose() - transpose tensor
# tf.reshape() - reshape tensor

# === AGGREGATION METHODS ===
print("\n=== AGGREGATION METHODS ===")
# tf.reduce_min() / tf.math.reduce_min() - find minimum value
# tf.reduce_max() / tf.math.reduce_max() - find maximum value  
# tf.reduce_mean() / tf.math.reduce_mean() - find mean value
# tf.reduce_sum() / tf.math.reduce_sum() - find sum of elements
# tf.argmax() / tf.math.argmax() - find index of maximum value
# tf.argmin() / tf.math.argmin() - find index of minimum value

# === TENSOR MANIPULATION ===
print("\n=== TENSOR MANIPULATION ===")
# tf.squeeze() - remove dimensions of size 1
# tf.expand_dims() - add new dimension
# tf.concat() - concatenate tensors
# tf.split() - split tensor into multiple tensors

# === ENCODING METHODS ===
print("\n=== ENCODING METHODS ===")
# tf.one_hot() - one-hot encoding
# Example: tf.one_hot(indices, depth) - converts indices to one-hot vectors

# === DATA TYPE CONVERSION ===  
print("\n=== DATA TYPE CONVERSION ===")
# tf.cast() - convert tensor to different data type
# Example: tf.cast(tensor, tf.float32)

# === COMPARISON OPERATIONS ===
print("\n=== COMPARISON OPERATIONS ===")
# tf.equal() - element-wise equality
# tf.greater() - element-wise greater than
# tf.less() - element-wise less than

# === EXAMPLES ===
print("\n=== EXAMPLES ===")
# One-hot encoding example
tensor = tf.constant([2, 1, 0, 3])
one_hot = tf.one_hot(tensor, depth=4)
print(f"Original: {tensor.numpy()}")
print(f"One-hot:\n{one_hot.numpy()}")

# Cast example
float_tensor = tf.constant([1.5, 2.7, 3.1])
int_tensor = tf.cast(float_tensor, tf.int32)
print(f"Float: {float_tensor.numpy()}")
print(f"Int: {int_tensor.numpy()}")

# Expand dims example
vector = tf.constant([1, 2, 3])
expanded = tf.expand_dims(vector, axis=0)
print(f"Original shape: {vector.shape}")
print(f"Expanded shape: {expanded.shape}")

=== TENSOR CREATION ===

=== TENSOR PROPERTIES ===

=== TENSOR OPERATIONS ===

=== AGGREGATION METHODS ===

=== TENSOR MANIPULATION ===

=== ENCODING METHODS ===

=== DATA TYPE CONVERSION ===

=== COMPARISON OPERATIONS ===

=== EXAMPLES ===
Original: [2 1 0 3]
One-hot:
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
Float: [1.5 2.7 3.1]
Int: [1 2 3]
Original shape: (3,)
Expanded shape: (1, 3)
